name = "rethink-form-handler"
main = "src/index.js"
compatibility_date = "2026-03-09"

# Ensure no [modules] header is present. 
# Cloudflare Pages handles the environment variables and bindings 
# automatically once you connect the GitHub repository.
